apiVersion: v1
kind: Service
metadata:
  name: {{ include "simple-app-2.fullname" . }}
  labels:
    {{- include "simple-app-2.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  selector:
    app: {{ include "simple-app-2.name" . }}