apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-app-2
  labels:
    app: simple-app-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app-2
  template:
    metadata:
      labels:
        app: simple-app-2
    spec:
      containers:
        - name: simple-app-2
          image: dockercaustav/simple-python-web-app-2:1.0.0
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
